spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/eshop
    username: postgres
    password: postgres
    hikari:
      schema: public

jwt:
  access-token-expiration: 3600000
  refresh-token-expiration: 86400000